tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "docker"
brew "git"
brew "mas"
brew "openssh"
brew "openssl"
brew "p7zip"
cask "android-studio"
cask "atom"
cask "docker"
cask "eclipse-jee"
cask "firefox"
cask "gimp"
cask "google-chrome-canary"
cask "google-japanese-ime"
caks "intellij-idea-ce"
cask "java"
cask "tor-browser"
cask "vagrant"
cask "virtualbox"
mas "1Password", id: 443987910
mas "Amphetamine", id: 937984704
mas "Xcode", id: 497799835
mas "Magnet", id: 441258766
