tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
cask "java"
brew "git"
brew "mas"
brew "node"
brew "openssl"
brew "docker"
brew "socat"
brew "p7zip"
cask "android-studio"
cask "appcleaner"
cask "atom"
cask "caffeine"
cask "eclipse-jee"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-japanese-ime"
cask "vagrant"
cask "virtualbox"
cask "xquartz"
mas "1Password", id: 443987910
mas "Kindle", id: 405399194
mas "Magnet", id: 441258766
mas "Xcode", id: 497799835
