tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "git"
brew "mas"
brew "openssh"
brew "openssl@1.1"
brew "p7zip"
cask "firefox"
cask "google-japanese-ime"
cask "visual-studio-code"
cask "virtualbox"
mas "Kindle", id 405399194
mas "Amphetamine", id: 937984704
mas "1Password", id: 443987910
mas "Xcode", id: 497799835
mas "Magnet", id: 441258766