tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "docker"
brew "git"
brew "mas"
brew "openjdk"
brew "openssh"
brew "p7zip"
brew "tmux"
brew "vim"
cask "android-studio"
cask "dbeaver-community"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-japanese-ime"
cask "microsoft-edge"
cask "vagrant"
cask "visual-studio-code"
cask "virtualbox"
mas "Kindle", id 405399194
mas "Amphetamine", id: 937984704
mas "1Password", id: 443987910
mas "Xcode", id: 497799835
mas "Magnet", id: 441258766