name: Application install on HomeBrew

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: macos-latest
    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_12.4.app/Contents/Developer'
      - name : Update Homebrew
        run: brew update
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Application
        run: ./mac/brewInstall.sh
