name: Application install on HomeBrew

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Application
        run: ./mac/brewInstall.sh
